---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gatus-secrets
  namespace: default
spec:
  encryptedData:
    TELEGRAM_CHAT_ID: AgCFcfL0rdgCtO/4ZwJ4UylOfzALvqU5kCYoR+4OALWDucIuxj+/Pgh1ntHoFfP0Z8fxSo8/brzHH2n3u5BnmkX4mK4LPw9LNU9kqm/iC7TVraAYeleuBQT6mRnLrrk/jz+zlQof6sfQkdjmpB46A+pym4ZX7v/GOn+Y0qj/cBACubY+RF+zBZsZN6BiLB/tLKz9j9VQ2jZa5XteLEp0JyQgnUQknDqkdN+WWjd2b1iJKkYNwaRguBW5m0CMTSStqYtSxyVG3D4iW+43VDbFLlSBbsnpnjHvYODkAfwffRBPHU2xZo9mkisGjJRoj86gvYqZMQ5ANee14wtm38VJjCFQJ4YmcdzrrmMG/EFknCYdQecbtxPcXmEuNq2L6WwMmjFCICjEQVT3RxYwhrHxphyRcpqlfaq/kkbkTcsaWH33RQb3Vpe5Uj9kPn/Nz3BD1OO+VLmp8Slkw0LcMZz0s6N7Ri90z94AUCJnbh2EVAeskxCGgvyeJ08mwzXoFMDtDdVWfYzPrRT867z5Hojhres+QSP+WOU+CW+TskOsKPFtc4lT1nf76vBWJ4YM1RUylt/pQ5rPUsKDqGNev8oS3vH/mtYlm+BpBtQ9fKui24McyUtuuWo76mDoOchc9lezDuZC2L7Tt0ytoN3enxNC772w+T4xnZ+IoJjry/QFsAYtoT7slXTluz3qGWkduFb7HkdqC20p3EWgiQ==
    TELEGRAM_TOKEN: AgBgjSNVEF8N75qxxtxlW5QkZ0YHvqjcfFGJz+IWeLxUCP5Mqx0MQ24E8jn17c5tu/LBoNvVqxZ4RDnl7nyz+qQiMfZa83JnzH3bB5RAPDmHmafTeP1JtZTDPfKlnaAkvpap/CgUKJZVLufq7RJAPHKAU5s0Tz7Zdbq4OZJfGwKQrXLMRvS5ViwA978oFZWNvVul+Qota2oEsxnIAzWFc+6+vNfcgp7OHRrWZ8uA/kEF9lfyjbbDeNoaHzIp/Nm10KG+ad2uI3Zd+bF6rfESLhw9bKFYw2cGTU3cFcgczy6Ol6cfh2duFg7VfLX6MS8chAZUqJ2ArUp20n9gjqRavxKvrdhr5ghvaMBcfm5OcuQgWczlPhoLHmyI8T4gJo1XJMgLd2H5/hz1GbqVITvlgVfkoaB3Aj6WjPp7ifA9io8ZCne4sVUzFtTbwPF+F0YFsGw7vzegAJNUrd9KPzrhXx7nfMm1GZCqW0icncU5WxTtu+0mc6i5QsYGe2SrRi4ma3+SDNr3NoyqGwcHWGH998+NcL1OY+O/BBilaQoC+UTGycmXnaAZQVocV0j3TcD7ioegOvqo51fvmSo7t6+s2sIIx2p5Ye++TcA8XYmmhykMMSVPc2CCUEPmfBWH0F+WImIyucLD3T/Dv0Ubfn0HMBRdejAuBRvO3OCRsWEWmHEemgDspVamN4Ba3wv6r6Eu5VaeY5qwtZEFhkuTYWtNaLhwGh5r5kk9D2OSZkdiwTWhlyg850mpzT2ZqkMPP9E=
  template:
    metadata:
      name: gatus-secrets
      namespace: default
    type: Opaque
