---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trek-secrets
  namespace: default
spec:
  encryptedData:
    ENCRYPTION_KEY: AgB8fZr+8R6JXB9ZUm11JwDl5mjk/xbfuZC1t8CEKnThepe2MkehnPrFJn/0iZa5SF6wJGxrSSXHLTSYBpPWJ6JGhXSFtVFhNnnCI+b1oP2MdIUyURwQfUuQoG0k/xeljbYCM9rmhDmRMqxWnw70lEVaj/18uOS2fKKqeLS9vUuw09tenJRVhEdjNGsyij6MgsU+IGBjQ7HRuFgLO7QT1V8xn/g4zEjm4fuhbcYoEV5no0q6vo0MlnzwvmPICm7PcI4VgoUUIPs3N8K/PTFgab/luzoVL8iA4jr4/8Ov4peZTfGwRdD+mEJI1HUZScrP5oYOUl/6pT6eytIh9aWF8LV7+S/MVyCHT01Lqq+UhX8TguFKADu4kO8R4YKTaC0x2dyyqcxdeTXmFf51L1dkgCvxwx3WcBeyQz1g976uzHWqsiUBMAqw7hfJR5GjJQTSY9NKWkyJ2HMRSsTN6mP9fqItWP9KAFxtJ+7JD0C7umDZo5v+fAdCE0bNO2n1tay2l/BkiJmOtBj0R6JJlIJJMhqNOBzVpZnRMpNfzzOgFQuAGP1U0JvHP7KlZvte+2bTnw2i888lhFGAySdzlizqT8qexvt4OcFiylzZo96DH6BqQoGJEVq+pL8iNiPiHsCVy89Dyttj2qliZcgbUxQFJn68gDQyz3Ps81veiuBbKzKVEYSfLKYU0SF52+F0lmJkHQFHu86K9EeRVHjvUZhGzbBNIbVjZ3wtApGnJELnM0+PM+eWktvNO9PIq9tJjJ6rRVyCeDXiQumRH1IBqdSXjmir
  template:
    metadata:
      name: trek-secrets
      namespace: default
    type: Opaque
