apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-data
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
