---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-secrets
  namespace: default
spec:
  encryptedData:
    VIKUNJA_SERVICE_JWTSECRET: AgApG4eTnXyntkTxmbTc607ClZ04DG8HLNjADcWCy3/vqqjljvtryqwekKmvE+p+29Xh5vhNPt6z+neod6yGk5QeIFKZJyd4pyKrtl86koze/tYVFP4Kj3uH9XluFF+UWlR7PTMTi33ZIBYGDvJpWjnNHTNLs9JnfzQKDyNB+s6CAxyifbmZ+JAjG4ODKjuZKmdn28h8BG5NyFvg2Bm6PDkDuCW3GLH4djPC7hRdE5NW5hvPDcnGGXicG/FccCeyH+bgaBTT/wFpr4UWs0uWTbAFnzx/xAd131z5RZSRt/IGcsoPPZuDtUGvr+dQNMugzIqE8+ezeEPzNbgw3OStb9Oj0J/JLV7rMZxcc+XVygE92/8/PfByA8g9UlBJOvtVlZwfFLbNk4ls6+wNSnPkMYgl8rbB+l1YgH8XkhgYg8oseuupMsMlgJ6qNwpqa5fKI4Q4/uOebHB030kFUMv9WKqiTfZpEbq3N7m4vEUMKQLqIg2Kl/4SCKeBb3Rd8ZEwCvVK/1GJhEsNRqUEq/QdTtbAdRNQuki9hob4os5jMOm0r+fYmNKrpPYPXgl4/SK+sRlAnfE3pW/Op2/fNe/0ivNX9eU3VkfG2r9H22AjqUgilo6yiCCmXt3H+uWG/vJuKt4qk9g5h1VcikBt7+9jLy80aFKBYE7V1/+4Ch9jnwsPDWLz17fEFSMPsbGtTLN4/F7LmBnzB1Ivc5P/5c/kpnWQ6z008ZERXOZcKK1TnxgCd9DOQwODCEAIe/njEg==
  template:
    metadata:
      name: vikunja-secrets
      namespace: default
    type: Opaque
